<a href="https://colab.research.google.com/github/AftabUdaipurwala/PythonBasics/blob/main/Python_Pandas_Tutorial_3_Different_Ways_Of_Creating_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from google.colab import drive
# Mounting the drive for loading the data
drive.mount('/content/drive')
!ls '/content/drive/MyDrive/py-master/pandas/3_different_ways_of_creating_dataframe'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
pandas_different_ways_of_creating_dataframe.ipynb  weather_data.xlsx
weather_data.csv

In [2]:
# Read data from a Csv file format
data = pd.read_csv('/content/drive/MyDrive/py-master/pandas/3_different_ways_of_creating_dataframe/weather_data.csv')
data.head(2)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [6]:
# read data from excel file format
df = pd.read_excel('/content/drive/MyDrive/py-master/pandas/3_different_ways_of_creating_dataframe/weather_data.xlsx','Sheet1')
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [9]:
# Reading from an dictionary
weather_data = {
    'day':['2017-01-01','2017-01-02','2017-01-03'],
    'temperature':[32,35,26],
    'windspeed':[6,7,6],
    'event':['Rain','Sunny','Snow']
}
df = pd.DataFrame(weather_data)
df

          day  temperature  windspeed  event
0  2017-01-01           32          6   Rain
1  2017-01-02           35          7  Sunny
2  2017-01-03           26          6   Snow

In [10]:
# Reading from a tuple
weather_data =[
               ('2017-01-01',32,6,'Rain'),
               ('2017-01-02',35,7,'Sunny'),
               ('2017-01-03',26,6,'Snow')
]
df = pd.DataFrame(weather_data, columns=['day','temperature','windspeed','event'])
df

          day  temperature  windspeed  event
0  2017-01-01           32          6   Rain
1  2017-01-02           35          7  Sunny
2  2017-01-03           26          6   Snow

In [11]:
# Reading from a list of dictionary 
weather_data =[
               {'day':'2017-01-01','temperature':32,'windspeed':6,'event':'Rain'},
               {'day':'2017-01-02','temperature':35,'windspeed':7,'event':'Sunny'},
               {'day':'2017-01-03','temperature':26,'windspeed':6,'event':'Snow'}
]
df = pd.DataFrame(weather_data)
df

          day  temperature  windspeed  event
0  2017-01-01           32          6   Rain
1  2017-01-02           35          7  Sunny
2  2017-01-03           26          6   Snow